version: '3'
services:
  app:
    image: proxyreverse
    environment:
      - REDIS_HOST=redis
    ports:
      - "9999:9999"
    command: go run main.go
    depends_on:
      - redis
  redis:
    image: "redis:alpine"