version: '3'
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    ports:
      - "9999:9999"
    volumes:
      - .:/go/src/app
    command: go run main.go
    depends_on:
      - redis
  redis:
    image: "redis:alpine"